"""Возможность ставить null в book_id

Revision ID: cd7e907e3433
Revises: c5b1cd17b16c
Create Date: 2023-12-17 20:37:36.564822

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd7e907e3433'
down_revision = 'c5b1cd17b16c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'book_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_requests_guid'), 'requests', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_guid'), table_name='requests')
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'book_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
