"""genre.title -> genre.name

Revision ID: e3c4faaa4c82
Revises: 46ef0ac7d8f1
Create Date: 2023-10-11 17:14:14.063976

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e3c4faaa4c82'
down_revision = '46ef0ac7d8f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('name', sa.String(), nullable=True, comment='Название жанра'))
    op.drop_column('genres', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Название жанра'))
    op.drop_column('genres', 'name')
    # ### end Alembic commands ###
