"""adding status to bookRequests

Revision ID: c5b1cd17b16c
Revises: b4865eccee1e
Create Date: 2023-12-04 15:17:23.673207

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c5b1cd17b16c'
down_revision = 'b4865eccee1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookcrossing_points', 'title',
               existing_type=sa.VARCHAR(),
               comment='Название точки буккроссинга',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Широта',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Долгота',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'address_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='Адрес',
               existing_nullable=False)
    op.create_index(op.f('ix_bookcrossing_points_guid'), 'bookcrossing_points', ['guid'], unique=True)
    op.add_column('requests', sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='bookrequeststatusenum'), nullable=True, comment='Статус запроса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    op.drop_index(op.f('ix_bookcrossing_points_guid'), table_name='bookcrossing_points')
    op.alter_column('bookcrossing_points', 'address_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Адрес',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Долгота',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Широта',
               existing_nullable=False)
    op.alter_column('bookcrossing_points', 'title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Название точки буккроссинга',
               existing_nullable=False)
    # ### end Alembic commands ###
