"""удален статус из книги

Revision ID: 90c6283c94c4
Revises: c20f5e595f73
Create Date: 2023-10-08 02:08:54.820352

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '90c6283c94c4'
down_revision = 'c20f5e595f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.UUID(), autoincrement=False, nullable=True, comment='Статус книги'))
    # ### end Alembic commands ###
