"""added address to bookcrossing points model

Revision ID: 8449bd66c5ca
Revises: e3c4faaa4c82
Create Date: 2023-11-11 19:06:48.255492

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8449bd66c5ca'
down_revision = 'e3c4faaa4c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookcrossing_points', sa.Column('address_text', sa.String(), nullable=True, comment='Адрес'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookcrossing_points', 'address_text')
    # ### end Alembic commands ###
